name: Executar e exportar notebook

on:
  push:
    branches: [main]  # Executa isso quando fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Um servidor Linux gratuito que o GitHub usa para rodar o código

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Pode usar outra versão se quiser

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar notebook e exportar para HTML
        run: |
          jupyter nbconvert --to html --execute previsao_insumos.ipynb --output previsao_insumos_resultado.html

      - name: Salvar resultado (artefato)
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-html
          path: previsao_insumos_resultado.html
