echo "name: Run notebook workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter
      - name: Execute notebook and export to HTML
        run: |
          jupyter nbconvert --to html --execute previsao_insumos.ipynb --output previsao_insumos_resultado.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-html
          path: previsao_insumos_resultado.html
" > .github/workflows/run_notebook.yml
