name: Executar notebook e exportar HTML

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter

      - name: Executar notebook e exportar para HTML
        run: |
          jupyter nbconvert --to html --execute previsao_insumos.ipynb --output previsao_insumos_resultado.html
