name: Executar e exportar notebook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter

      - name: Executar notebook e exportar para HTML
        run: |
          jupyter nbconvert --to html --execute previsao_insumos.ipynb --output previsao_insumos_resultado.html

      - name: Salvar artefato do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-html
          path: previsao_insumos_resultado.html
